title: Yet another fullstack developer blog
email: bocharoviliav@gmail.com
description: >-
  Hi all! My name is Ilia Bocharov. I'm fullstack developer.
  My main programming language is Java, i've writing code on Java
  since 2015. In 2018 i've started write on Typescript and very exited with it.
  I'm currently learning Rust and want to share part of my experience here.
baseurl: ""
url: "https://bocharoviliyav.github.io"
twitter_username: bocharoviliyav
github_username:  bocharoviliyav

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
