title: Yet another fullstack developer blog
author: Ilia Bocharov
email: bocharoviliav@gmail.com
description: >-
  Java, Typescript, Rust and DevOps stuff will be here.
baseurl: ""
url: "https://bocharoviliyav.github.io"
twitter_username: bocharoviliyav
github_username:  bocharoviliyav
linkedin_username: bocharoviliyav
telegram_username: bocharoviliyav

# Build settings
markdown: kramdown
theme: minima

jekyll_analytics:
  GoogleAnalytics:
    id: 259558923

plugins:
  - jekyll-analytics
