title: Yet another fullstack developer blog
author: Ilia Bocharov
email: bocharoviliav@gmail.com
description: >-
  Java, Typescript, Rust and DevOps stuff will be here.
baseurl: ""
url: "https://bocharoviliyav.blog"
twitter_username: bocharoviliyav
github_username:  bocharoviliyav
linkedin_username: bocharoviliyav
telegram_username: bocharoviliyav
google_analytics: G-PE6HGY6KFF

# Build settings
markdown: kramdown
theme: minima

pwa:
  enabled: true
  precache_recent_posts_num: 10

plugins:
  - jekyll-pwa-plugin
  - jekyll-sitemap


