title: Yet another fullstack developer blog
email: bocharoviliav@gmail.com
description: >-
  Java, Typescript, Rust and DevOps stuff will be here.
baseurl: ""
url: "https://bocharoviliyav.github.io"
twitter_username: bocharoviliyav
github_username:  bocharoviliyav

# Build settings
markdown: kramdown
theme: minima
google_analytics: 259558923
plugins:
  - jekyll-feed
