title: Yet another fullstack developer blog
author: Ilia Bocharov
email: bocharoviliav@gmail.com
description: >-
  Java, Typescript, Go and DevOps stuff will be here.
baseurl: ""
url: "https://bocharoviliyav.blog"
twitter_username: bocharoviliyav
github_username:  bocharoviliyav
linkedin_username: bocharoviliyav
telegram_username: bocharoviliyav
google_analytics: G-PE6HGY6KFF

# Build settings
markdown: kramdown
theme: minima

plugins:
  - jekyll-sitemap
  - jekyll-feed


